In [1]:
import numpy as np
# N-dimensioanal numpy arrays
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int64


In [2]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


In [7]:
'''
The Colon (:)
The colon is used to specify a range of indices in a dimension. It means 
"select all elements along this dimension." In the context of a 
two-dimensional array, : will select all rows or all columns, 
depending on where it is placed.
'''

first_column= two_dimension_array[:,0]#The colon ':' means "select all rows."
second_column = two_dimension_array[:,1]#1 = column index
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)


First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#Slicing Numpy array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]#not inclusive
print(two_dimension_array)
print('\n')
print(first_two_rows_and_columns)
print('\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2]
 [4 5]]




In [17]:
#Reverse rows
two_dimension_array[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [18]:
#reverse rows and columns
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])