In [10]:
def space():
    print('\n')
    
#Representing missing values
import numpy as np    
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [11]:
#
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44
print('\n')
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [12]:
    # Numpy Zeroes, making an array with default values
    # numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
print(numpy_zeroes)
space()
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
n_multiplier = 10 #any number
n = numpy_ones * n_multiplier
print(n)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [14]:
# Reshape, change the grouping of multidimensional arrays
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [16]:
flattened = reshaped.flatten()
print(flattened)

[1 2 3 4 5 6]


In [21]:
## Horitzontal Stack, instead of adding elements of 2 arrays to each corresponding index, append the second 
## array to the first to make new single list
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])


print(np_list_one + np_list_two)
print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))
space()
## Vertical Stack, append arrays to new multi-dimensional array
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))



[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


Vertical Append: [[1 2 3]
 [4 5 6]]


In [27]:
#Generating random numbers
    # Generate a random float  number
random_float = np.random.random()
print(random_float)
space()
    # Generate a random float  number
random_floats = np.random.random(5)
print(random_floats)
space()
    # Generating a random integers between 0 and 10
random_int = np.random.randint(0, 11)
print(random_int)
    # Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size=10)
print(random_int)

0.9933029231033579


[0.82835193 0.62261187 0.96936946 0.64279422 0.7394659 ]


3
[6 8 8 5 6 9 8 7 8 9]


In [28]:
#Generating random numbers
    # np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array


array([ 67.33350584,  71.10756862,  66.95258763,  76.06421614,
        70.73887738,  75.62280154,  47.73150944,  95.1913085 ,
        74.25181194,  48.50714889,  70.58312909,  74.50405016,
        62.76088706,  83.31417617,  77.8573052 ,  92.85473008,
        78.6945403 ,  92.11119635,  75.23886881,  73.1753042 ,
        82.76001224,  65.13124406,  61.03861265,  95.37282434,
        68.9577453 ,  90.43091092,  66.71966678,  71.84296669,
        75.51017435,  60.96101169,  53.90194934,  88.74201054,
        85.82982543,  81.90457653,  82.64439827,  54.07393542,
        98.30449023, 102.31727178,  62.30841559, 104.20702263,
        83.74624356,  99.10686525,  90.93659542,  94.03541518,
        51.84295209,  79.1799344 ,  94.7116433 ,  93.86847717,
        85.7385167 ,  86.12996706,  92.11035956,  92.62178216,
        77.4916591 ,  74.56111876,  86.70765018,  96.23898859,
        90.23475807,  92.54589587,  83.23271052,  81.99953114,
        67.48120466,  72.28611636,  75.71826882,  91.87

In [30]:

four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))
print(four_by_four_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])