In [10]:
def space():
    print('\n')
    
#Representing missing values
import numpy as np    
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [11]:
#
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44
print('\n')
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [12]:
    # Numpy Zeroes, making an array with default values
    # numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
print(numpy_zeroes)
space()
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
n_multiplier = 10 #any number
n = numpy_ones * n_multiplier
print(n)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
